import React from "react";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function Home() {
  const fatchdata = await fetch("https://jsonplaceholder.typicode.com/todos/1");
  console.log(fatchdata);
  const todo = await fatchdata.json();
  return (
    <div>
      <div className="text-3xl font-bold flex min-h-screen flex-col items-center justify-center p-24">
        <h1 className="text-3xl font-bold flex min-h-screen flex-col items-center justify-center p-24">
          {todo ? (
            <div>
              <h1>{todo.title}</h1>
              <p>Completed: {todo.completed ? "Yes" : "No"}</p>
            </div>
          ) : (
            <p>Loading...</p>
          )}
        </h1>
      </div>
    </div>
  );
}
